version: "3.7"
services:
    api:
        image: booksbackend
        depends_on:
            - sql
        ports:
            - 80:80
        environment:
            - ConnectionStrings_books=server=sql;database=books;user=sa;password=TokyoJoe138!
    sql:
        image: justinmckenna/bookssql
        ports:
            - 1433:1433